WITH NEW_TABLE AS (
    SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, 
           PRODUCT_ID, 
           USER_ID,
           SALES_AMOUNT 
    FROM ONLINE_SALE

    UNION

    SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, 
           PRODUCT_ID, 
           NULL AS USER_ID,
           SALES_AMOUNT
    FROM OFFLINE_SALE
)

SELECT * FROM NEW_TABLE
WHERE SALES_DATE LIKE "2022-03%"
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID
