-- 코드를 입력하세요
WITH AVGSCORE AS (
    SELECT REST_ID, ROUND(AVG(REVIEW_SCORE),2) AS AVG_SCORE
    FROM REST_REVIEW
    GROUP BY REST_ID
)

SELECT i.REST_ID, i.REST_NAME, i.FOOD_TYPE, i.FAVORITES,i.ADDRESS, a.AVG_SCORE AS SCORE
FROM REST_INFO i JOIN AVGSCORE a ON i.REST_ID = a.REST_ID
WHERE i.ADDRESS LIKE "서울%"
ORDER BY a.AVG_SCORE DESC, i.FAVORITES DESC