-- 코드를 입력하세요
SELECT YEAR(s.SALES_DATE) AS YEAR, MONTH(s.SALES_DATE) AS MONTH, i.GENDER, count(DISTINCT(s.USER_ID)) AS USERS
FROM ONLINE_SALE s JOIN USER_INFO i ON s.USER_ID = i.USER_ID
WHERE i.GENDER IS NOT NULL
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), i.GENDER
ORDER BY YEAR(SALES_DATE), MONTH(SALES_DATE), i.GENDER