-- 코드를 입력하세요
with MOST_REVIEW AS (
    SELECT MEMBER_ID, count(*) FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY count(*) DESC
    LIMIT 1
)

SELECT mp.MEMBER_NAME, r.REVIEW_TEXT, DATE_FORMAT(r.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW r 
INNER JOIN MOST_REVIEW mr ON r.MEMBER_ID = mr.MEMBER_ID
JOIN MEMBER_PROFILE mp ON r.MEMBER_ID = mp.MEMBER_ID
ORDER BY r.REVIEW_DATE, r.REVIEW_TEXT